from .circuit import ImmutableQuantumCircuit, QuantumCircuit
from .gate import QuantumGate

def inverse_gate(gate: QuantumGate) -> QuantumGate: ...
def inverse_circuit(circuit: ImmutableQuantumCircuit) -> QuantumCircuit: ...
