[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning", "setuptools"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
name = "quri-parts"
version = "0.0.0"
description = "Platform-independent quantum computing library"
license = "Apache-2.0"
authors = ["QURI Parts Authors <opensource@qunasys.com>"]
readme = "README.md"
repository = "https://github.com/QunaSys/quri-parts"
documentation = "https://quri-parts.qunasys.com"
keywords = ["quantum", "quantum computing"]
classifiers = ["Topic :: Scientific/Engineering :: Physics", "Typing :: Typed"]
packages = [{ include = "quri_parts" }]

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"

[tool.poetry.dependencies]
python = "^3.9.8"
quri-parts-rust = "*"
quri-parts-core = "*"
quri-parts-circuit = "*"
quri-parts-algo = "*"
quri-parts-chem = "*"

quri-parts-qulacs = { version = "*", optional = true }
quri-parts-braket = { version = "*", optional = true, python = "<3.14" }
quri-parts-qiskit = { version = "*", optional = true, python = "<3.14" }
quri-parts-cirq = { version = "*", optional = true }
quri-parts-openfermion = { version = "*", optional = true }
quri-parts-stim = { version = "*", optional = true }
quri-parts-openqasm = { version = "*", optional = true }
quri-parts-quantinuum = { version = "*", optional = true }
quri-parts-ionq = { version = "*", optional = true }
quri-parts-itensor = { version = "*", optional = true }
quri-parts-pyscf = { version = "*", optional = true }
quri-parts-tensornetwork = { version = "*", optional = true }
quri-parts-tket = { version = "*", optional = true, python = ">=3.10" }
quri-parts-qsub = { version = "*", optional = true, python = ">=3.10" }
quri-parts-qret = { version = "*", optional = true, python = ">=3.10" }

[tool.poetry.extras]
qulacs = ["quri-parts-qulacs"]
braket = ["quri-parts-braket"]
qiskit = ["quri-parts-qiskit"]
cirq = ["quri-parts-cirq"]
openfermion = ["quri-parts-openfermion"]
stim = ["quri-parts-stim"]
openqasm = ["quri-parts-openqasm"]
quantinuum = ["quri-parts-quantinuum"]
ionq = ["quri-parts-ionq"]
itensor = ["quri-parts-itensor"]
pyscf = ["quri-parts-pyscf"]
tket = ["quri-parts-tket"]
tensornetwork = ["quri-parts-tensornetwork"]
qsub = ["quri-parts-qsub"]
