[tool.poetry]
name = "quri-vm"
version = "0.24.0"
description = ""
authors = ["QunaSys"]
readme = "README.md"
packages = [{ include = "quri_vm" }]

[tool.poetry.dependencies]
python = "<4,>=3.10"
quri-parts-circuit = "*"
quri-parts-qulacs = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
