[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "quri-vm"
version = "0.26.4"
description = ""
authors = [{ name = "QunaSys" }]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "quri-parts-circuit",
    "quri-parts-qulacs",
    "matplotlib>=3.10.1,<4.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["quri_vm"]

[tool.hatch.build.targets.sdist]
only-include = ["quri_vm"]

[tool.uv.sources]
quri-parts-circuit = { path = "../quri-parts/packages/circuit", editable = true }
quri-parts-qulacs = { path = "../quri-parts/packages/qulacs", editable = true }

[tool.isort]
profile = "black"
known_first_party = ["quri_vm"]
