[tool.poetry]
name = "quri-algo"
version = "0.25.0"
description = "Algorithm library based on QURI Parts"
license = "MIT"
authors = ["QunaSys"]
readme = "README.md"
repository = "https://github.com/QunaSys/quri-algo"
documentation = "https://quri-sdk.qunasys.com"
keywords = ["quantum", "quantum computing"]
classifiers = ["Topic :: Scientific/Engineering :: Physics", "Typing :: Typed"]
packages = [{ include = "quri_algo" }]

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"

[tool.poetry.dependencies]
python = ">=3.10,<4"
quri-parts-core = "*"
quri-parts-circuit = "*"
quri-parts-algo = "*"
quri-parts-chem = "*"
quri-parts-qulacs = "*"
quri-parts-pyscf = {version = "*", optional = true}
quri-parts-openfermion = {version = "*", optional = true}
quri-parts-qsub = "*"
quri-parts-rust = "*"
pytest = "^8.3.3"

[tool.poetry.extras]
openfermion = ["quri-parts-openfermion"]
pyscf = ["quri-parts-pyscf"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_first_party = ["quri_algo"]
known_third_party = ["quri_vm", "quri_parts"]
