name: Check modified notebooks

on:
  pull_request:
    paths:
      - 'notebooks/quri_sdk_notebooks/**.ipynb'

defaults:
  run:
    working-directory: notebooks


jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: git config
      run: |
        git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf https://github.com/

    - name: Install jq
      uses: dcarbone/install-jq-action@v3
      with:
        version: '1.6'
        force: true

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        version: "0.11.17"
        python-version: "3.11"
        enable-cache: true
        cache-dependency-glob: "notebooks/uv.lock"

    - run: |
        git fetch

    - run: |
        uv sync --locked

    - run: |
        for f in $(git diff --name-only origin/main quri_sdk_notebooks/ | grep .ipynb)
        do
          if grep -Fxq "${f#notebooks/}" .exclude
          then
            echo "Skipping execution of ${f#notebooks/}"
          else
            echo "Executing ${f#notebooks/}"
            uv run --no-sync jupyter execute --inplace --JupyterApp.log_level=50 "${f#notebooks/}"
          fi
        done
