name: Check all notebooks

on:
  pull_request:
    paths:
      - notebooks/uv.lock
      - notebooks/pyproject.toml

defaults:
  run:
    working-directory: notebooks

jobs:
  execute-all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: git config
      run: |
        git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf https://github.com/

    - name: Install jq
      uses: dcarbone/install-jq-action@v3
      with:
        version: '1.6'
        force: true

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        version: "0.11.17"
        python-version: "3.11"
        enable-cache: true
        cache-dependency-glob: "notebooks/uv.lock"

    - run: |
        uv sync --locked

    - run: |
        for f in $(find quri_sdk_notebooks -mindepth 1 -type f -name *.ipynb)
        do
          if grep -Fxq $f .exclude
          then
            echo "Skipping execution of $f"
          else
            echo "Executing $f"
            start=$(date +%s)
            uv run --no-sync jupyter execute --inplace --JupyterApp.log_level=50 $f
            end=$(date +%s)
            seconds=$((end-start))
            echo "Elapsed: $(($seconds / 3600))hrs $((($seconds / 60) % 60))min $(($seconds % 60))sec"
          fi
        done
