name: Check notebook diff

on:
  pull_request:
    paths:
      - 'notebooks/quri_sdk_notebooks/**.ipynb'

defaults:
  run:
    working-directory: notebooks

jobs:
  check-clean:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install jq
      uses: dcarbone/install-jq-action@v3
      with:
        version: '1.6'
        force: true

    - run: |
        make -s clean-nb

    - run: |
        git diff --exit-code
