name: QURI Parts Lint

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/packages/**/*.rs
      - quri-parts/rust/**/*.rs
      - quri-parts/pyproject.toml
      - quri-parts/.flake8
      - pyproject.toml
      - uv.lock
      - .github/workflows/quri-parts-lint.yml
      - .github/actions/quri-parts/rust-install-cache/action.yml
  push:
    branches: [main]


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        version: "0.11.17"
        python-version: "3.10"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: |
        uv sync --locked --group lint

    - uses: ./.github/actions/quri-parts/rust-install-cache
      with:
        toolchain: "nightly"
        additional-key: "lint"

    - name: Install fmt
      working-directory: quri-parts
      run: rustup component add rustfmt

    - name: Run format
      working-directory: quri-parts
      run: cargo fmt --all -- --check
      if: success() || failure()

    - name: Run isort
      run: uv run --no-sync isort quri-parts/packages --check --diff
      if: success() || failure()

    - name: Run black
      run: uv run --no-sync black --config .black.toml quri-parts/packages --check
      if: success() || failure()

    - name: Run flake8
      run: uv run --no-sync flake8 quri-parts/packages --config .flake8
      if: success() || failure()

    - name: Run docformatter
      run: uv run --no-sync docformatter -c -r quri-parts/packages
      if: success() || failure()
