name: QURI Algo Typecheck

on:
  pull_request:
    paths:
      - quri-algo/pyproject.toml
      - quri-algo/**.py
      - pyproject.toml
      - poetry.lock
      - mypy.ini
      - .github/workflows/quri-algo-typecheck.yml
  push:
    branches: [main]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-algo/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        poetry env use python3.11
        poetry install --only main,typecheck --extras algo

    - run: poetry run mypy quri-algo/tests quri-algo/quri_algo