name: QURI Parts Type check

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/mypy.ini
      - quri-parts/pyproject.toml
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-parts-typecheck.yml
      - .github/actions/python-poetry-install/action.yml
  push:
    branches: [main]

jobs:
  typecheck:

    strategy:
      matrix:
        python_version:
          - '3.10'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: ${{ matrix.python_version }}

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: poetry-${{ runner.os }}-py${{ matrix.python_version }}-quri-parts-type-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env use ${{ matrix.python_version }}
        poetry install --with dev,typecheck --sync

    - name: Cache mypy cache
      uses: actions/cache@v4
      with:
        path: quri-parts/.mypy_cache
        key: mypy-${{ runner.os }}-${{ matrix.python_version }}-${{ hashFiles('quri-parts/**/*.py') }}
        restore-keys: |
          mypy-${{ runner.os }}-${{ matrix.python_version }}-

    - name: Run mypy
      run: poetry run bash -c 'cd quri-parts && mypy .'
      if: success() || failure()
