name: QURI Parts Lint

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/packages/**/*.rs
      - quri-parts/rust/**/*.rs
      - quri-parts/pyproject.toml
      - quri-parts/.flake8
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-parts-lint.yml
      - .github/actions/python-poetry-install/action.yml
      - .github/actions/quri-parts/rust-install-cache/action.yml
  push:
    branches: [main]


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: '3.10'

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: poetry-${{ runner.os }}-py310-quri-parts-lint-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env use 3.10
        poetry install --with dev,lint --sync

    - uses: ./.github/actions/quri-parts/rust-install-cache
      with:
        toolchain: "nightly"
        additional-key: "lint"

    - name: Install fmt
      working-directory: quri-parts
      run: rustup component add rustfmt

    - name: Run format
      working-directory: quri-parts
      run: cargo fmt --all -- --check
      if: success() || failure()

    - name: Run isort
      run: poetry run isort quri-parts/packages --check --diff
      if: success() || failure()

    - name: Run black
      run: poetry run black quri-parts/packages --check
      if: success() || failure()

    - name: Run flake8
      run: poetry run flake8 quri-parts/packages --config .flake8 --exclude quri-parts/packages/qret
      if: success() || failure()

    - name: Run docformatter
      run: poetry run docformatter -c -r quri-parts/packages
      if: success() || failure()
