name: QURI Parts Document

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/docs/**
      - quri-parts/pyproject.toml
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-parts-doc.yml
      - .github/actions/python-poetry-install/action.yml
  push:
    branches: [main]


jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: '3.9'

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: poetry-${{ runner.os }}-py39-quri-parts-doc-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env use 3.9
        poetry install --only doc --sync

    - uses: actions/cache@v4
      with:
        path: |
          ~/.julia/
        key: ci-${{ runner.os }}-julia-${{ hashFiles('poetry.lock') }}-cache
        restore-keys: ci-${{ runner.os }}-julia-

    - name: Download pandoc
      if: steps.cache-pandoc.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb

    - name: Install pandoc
      run: |
        yes | sudo dpkg -i pandoc-2.18-1-amd64.deb

    - run: |
        poetry run julia -e 'using Pkg; Pkg.add("PythonCall")'
  
    - run: poetry run bash -c 'cd quri-parts/docs && make html'

    - name: deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: 'quri-parts/docs/_build'
        production-branch: main
        alias: deploy-preview-${{ github.event.number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        enable-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: c809dd00-1b20-41de-adc9-ad4c882d452d
