name: QURI Algo Test

on:
  pull_request:
    paths:
      - quri-algo/quri_algo/**/*.py
      - quri-algo/tests/**/*.py
      - quri-algo/pyproject.toml
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-algo-test.yml
      - .github/actions/python-poetry-install/action.yml
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.10'

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
        key: poetry-${{ runner.os }}-py${{ env.PYTHON_VERSION }}-quri-algo-test-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env use $PYTHON_VERSION

        # prevent `no quri_parts.rust.quri_parts_rust module` error occuring with wrong cache
        poetry run pip install quri-parts/packages/rust

        poetry install --only main,dev

    - name: Run pytest
      run: poetry run pytest quri-algo/tests/
