name: QURI Parts Test

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/packages/**/*.rs
      - quri-parts/./**/Cargo.toml
      - quri-parts/./**/Cargo.lock
      - quri-parts/rust/**/*.rs
      - quri-parts/**/*.jl
      - quri-parts/pyproject.toml
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-parts-test.yml
      - .github/actions/python-poetry-install/action.yml
      - .github/actions/quri-parts/rust-install-cache/action.yml
  push:
    branches: [main]


jobs:
  test:

    strategy:
      matrix:
        python_version:
          - '3.9'
          - '3.10'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: ${{ matrix.python_version }}

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
        key: poetry-${{ runner.os }}-py${{ matrix.python_version }}-quri-parts-test-${{ hashFiles('poetry.lock') }}

    - uses: ./.github/actions/quri-parts/rust-install-cache
      with:
        toolchain: "stable"
        additional-key: "test"

    - uses: actions/cache@v4
      with:
        path: |
          ~/.julia/
        key: ci-${{ runner.os }}-julia-${{ hashFiles('poetry.lock') }}-cache
        restore-keys: ci-${{ runner.os }}-julia-

    - name: Run Rust tests
      working-directory: quri-parts
      run: cargo test --workspace

    - name: Install dependencies
      run: |
        poetry env use ${{ matrix.python_version }}
        poetry run pip install -vvv -e quri-parts/packages/rust
        poetry install -vvv --only main,dev

    - name: Detect Julia project
      id: julia_project
      run: |
        poetry run python -c "import juliapkg; print('PROJECT={}'.format(juliapkg.project()))" | sed -ne '/^PROJECT=/p' >> "$GITHUB_OUTPUT"

    - name: Prepare Julia deps
      run: |
        poetry run julia  "--project=${{ steps.julia_project.outputs.PROJECT }}" -e 'using Pkg; Pkg.add("PythonCall"); Pkg.instantiate()'

    - name: Run pytest
      run: poetry run bash -c 'cd quri-parts && pytest'
