name: QURI VM Lint

on:
  pull_request:
    paths:
      - quri-vm/**/*.py
      - quri-vm/pyproject.toml
      - quri-vm/.flake8
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-vm-lint.yml
      - .github/actions/python-poetry-install/action.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.10'

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: poetry-${{ runner.os }}-py${{ env.PYTHON_VERSION }}-quri-vm-lint-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env use $PYTHON_VERSION
        poetry install --with dev,lint,typecheck --sync

    - name: Run isort
      run: poetry run bash -c 'cd quri-vm && isort . --check --diff'
      if: success() || failure()

    - name: Run black
      run: poetry run bash -c 'cd quri-vm && black . --check'
      if: success() || failure()

    - name: Run flake8
      run: poetry run bash -c 'cd quri-vm && flake8 . --config .flake8'
      if: success() || failure()

    - name: Run mypy
      run: poetry run bash -c 'cd quri-vm && mypy .'
      if: success() || failure()
