name: QURI Algo Lint

on:
  pull_request:
    paths:
      - .flake8
      - quri-algo/pyproject.toml
      - pyproject.toml
      - poetry.lock
      - quri_algo/**.py
      - .github/workflows/quri-algo-lint.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-algo/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        poetry env use python3.11
        poetry install --only lint --extras algo

    - run: poetry run isort quri-algo --check --diff
      if: success() || failure()

    - run: poetry run black quri-algo --check
      if: success() || failure()

    - run: poetry run flake8 quri-algo --show-source
      if: success() || failure()

    - run: poetry run docformatter -c -r quri-algo
      if: success() || failure()
