name: QURI Algo Lint

on:
  pull_request:
    paths:
      - quri-algo/quri_algo/**/*.py
      - quri-algo/pyproject.toml
      - quri-algo/.flake8
      - pyproject.toml
      - poetry.lock
      - .github/workflows/quri-algo-lint.yml
      - .github/actions/python-poetry-install/action.yml
  push:
    branches: [main]


jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.10'

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/python-poetry-install
      with:
        poetry-version: '1.8.5'
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Poetry environment
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ runner.os }}-py${{ env.PYTHON_VERSION }}-quri-algo-lint-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env use $PYTHON_VERSION
        poetry install --only lint

    - name: Run isort
      run: poetry run bash -c 'cd quri-algo && isort quri_algo --check --diff'
      if: success() || failure()

    - name: Run black
      run: poetry run bash -c 'cd quri-algo && black quri_algo --check'
      if: success() || failure()

    - name: Run flake8
      run: poetry run bash -c 'cd quri-algo && flake8 quri_algo --show-source'
      if: success() || failure()

    - name: Run docformatter
      run: poetry run bash -c 'cd quri-algo && docformatter -c -r quri_algo'
      if: success() || failure()
