name: QURI VM Lint

on:
  pull_request:
    paths:
      - 'quri-vm/**.py'
      - quri-vm/pyproject.toml
      - poetry.lock
      - .flake8
      - mypy.ini
      - pyproject.toml
      - .github/workflows/quri-vm-lint.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-vm/setup
      with:
        poetry-version: '2.2.1'
        python-version: '3.10'

    - run: |
        poetry env use 3.10
        poetry install -vvv --only dev,typecheck --extras vm

    - run: poetry run isort quri-vm --check --diff
      if: success() || failure()

    - run: poetry run black quri-vm --check
      if: success() || failure()

    - run: poetry run flake8 quri-vm
      if: success() || failure()

    - run: poetry run mypy quri-vm
      if: success() || failure()
