name: Test QURI Algo

on:
  pull_request:
    paths:
      - quri-algo/pyproject.toml
      - quri-algo/poetry.lock
      - quri-algo/quri_algo/**.py
      - .github/workflows/quri_algo_test.yml
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-algo/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        cd quri-algo/
        poetry env use python3.11
        poetry install

    - run: |
        cd quri-algo/
        poetry run pytest tests/